---
mongo:
  db: timeline_words
  words_collection: words
  log_collection: log
twitter:
  consumer_key: YOUR_CONSUMER_KEY
  consumer_secret: YOUR_CONSUMER_SECRET
  oauth_token: YOUR_OAUTH_TOKEN
  oauth_token_secret: YOUR_OAUTH_TOKEN_SECRET
bot:
  screen_name: YOUR_BOT_SCREEN_NAME
